Update the error message
Co-authored-by: Ravi <7014230+arelra@users.noreply.github.com>

diff --git a/.github/workflows/e2e-playwright.yml b/.github/workflows/e2e-playwright.yml
--- a/.github/workflows/e2e-playwright.yml
+++ b/.github/workflows/e2e-playwright.yml
@@ -66,7 +66,7 @@ jobs:
 
       - name: Start DCR in a container step failed
         if: ${{ failure() && steps.start-dcr-container.conclusion == 'failure' && steps.start-dcr-container.outputs.exitcode == 125 }}
-        run: echo "Run the DCR main build in order to create a new container image." && exit 1
+        run: echo "Unable to fetch a DCR container image from the registry. Run the DCR main build in order to create a new container image." && exit 1
 
       - name: Install Playwright Browsers
         run: pnpm playwright install --with-deps chromium
